# Generated by Django 3.1.2 on 2020-10-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoAuthorship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('first_author_id', models.IntegerField()),
                ('second_author_id', models.IntegerField()),
                ('paper_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pii', models.IntegerField()),
                ('title', models.TextField(max_length=200)),
                ('abstract', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('url', models.CharField(max_length=200)),
                ('journal_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PotentialCoAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('first_author_id', models.IntegerField()),
                ('second_author_id', models.IntegerField()),
                ('paper_id', models.IntegerField(default=0)),
            ],
        ),
    ]
