# Generated by Django 3.1.2 on 2020-10-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coauthorship',
            name='date',
        ),
        migrations.RemoveField(
            model_name='potentialcoauthor',
            name='date',
        ),
        migrations.RemoveField(
            model_name='potentialcoauthor',
            name='paper_id',
        ),
        migrations.AlterField(
            model_name='coauthorship',
            name='paper_id',
            field=models.IntegerField(),
        ),
    ]
